#include "defs.h"
#include <linux/input-event-codes.h>
#include <linux/input.h>

struct device devices[2] = {{0, 0, "usb-Evision_RGB_Keyboard-event-kbd"},
                            {1, 0, "usb-04d9_USB_Gaming_Mouse-if01-event-kbd"}};

char mouse_id = 1;

int profile_ind = 0;
int profile_max_ind = 4;
int index_render_offset = -1;

struct profile presets[] = {
    {0,
     {{9, "Switches profile to next", SwitchProfile, Short, {}}},
     "None",
     0x7A7A7AFF},
    {0,
     {
         {2,
          "\"Thanks!\"",
          Default,
          Short,
          {{1, 0, KEY_Z, EV_KEY}, {1, 0, KEY_2, EV_KEY}}},
         {3,
          "\"Spy!\"",
          Default,
          Short,
          {{1, 0, KEY_X, EV_KEY}, {1, 0, KEY_2, EV_KEY}}},
         {4,
          "\"Yes\"",
          Default,
          Short,
          {{1, 0, KEY_Z, EV_KEY}, {1, 0, KEY_7, EV_KEY}}},
         {5,
          "\"No\"",
          Default,
          Short,
          {{1, 0, KEY_Z, EV_KEY}, {1, 0, KEY_8, EV_KEY}}},
         {6,
          "\"Incoming\"",
          Default,
          Short,
          {{1, 0, KEY_X, EV_KEY}, {1, 0, KEY_1, EV_KEY}}},
         {7,
          "\"Sentry Ahead!\"",
          Default,
          Short,

          {{1, 0, KEY_X, EV_KEY}, {1, 0, KEY_3, EV_KEY}}},
         {8, "Shows help", Help, Short, {}},
         {9, "Switches profile to next", SwitchProfile, Short, {}},
     },
     "Team Fortress 2",
     0xF86A21FF},
    {0,
     {
         {2,
          "Operator 1 Skill/Ultimate",
          Default,
          Long,
          {{1, 0, KEY_1, EV_KEY}}},
         {3,
          "Operator 2 Skill/Ultimate",
          Default,
          Long,
          {{1, 0, KEY_2, EV_KEY}}},
         {4,
          "Operator 3 Skill/Ultimate",
          Default,
          Long,
          {{1, 0, KEY_3, EV_KEY}}},
         {5,
          "Operator 4 Skill/Ultimate",
          Default,
          Long,
          {{1, 0, KEY_4, EV_KEY}}},

         {8, "Shows help", Help, Short, {}},
         {9, "Switches profile to next", SwitchProfile, Short, {}},
     },
     "Arknights: Endfield",
     0xDDF72FFF},
    {0,
     {
         {2,
          "Trademark",
          Default,
          Short,
          {
              {1, 0, KEY_LEFTCTRL, EV_KEY, Hold},
              {1, 0, KEY_LEFTSHIFT, EV_KEY, Hold},
              {1, 0, KEY_U, EV_KEY},
              {1, 0, KEY_2, EV_KEY},
              {1, 0, KEY_1, EV_KEY},
              {1, 0, KEY_2, EV_KEY},
              {1, 0, KEY_2, EV_KEY},
              {1, 0, KEY_LEFTCTRL, EV_KEY, Unhold},
              {1, 0, KEY_LEFTSHIFT, EV_KEY, Unhold},
          }},
         {3,
          "Empty array",
          Default,
          Short,
          {
              {1, 0, KEY_LEFTCTRL, EV_KEY, Hold},
              {1, 0, KEY_LEFTSHIFT, EV_KEY, Hold},
              {1, 0, KEY_U, EV_KEY},
              {1, 0, KEY_2, EV_KEY},
              {1, 0, KEY_3, EV_KEY},
              {1, 0, KEY_0, EV_KEY},
              {1, 0, KEY_0, EV_KEY},
              {1, 0, KEY_LEFTCTRL, EV_KEY, Unhold},
              {1, 0, KEY_LEFTSHIFT, EV_KEY, Unhold},
          }},
         {4,
          "Warning",
          Default,
          Short,
          {
              {1, 0, KEY_LEFTCTRL, EV_KEY, Hold},
              {1, 0, KEY_LEFTSHIFT, EV_KEY, Hold},
              {1, 0, KEY_U, EV_KEY},
              {1, 0, KEY_2, EV_KEY},
              {1, 0, KEY_6, EV_KEY},
              {1, 0, KEY_A, EV_KEY},
              {1, 0, KEY_0, EV_KEY},
              {1, 0, KEY_LEFTCTRL, EV_KEY, Unhold},
              {1, 0, KEY_LEFTSHIFT, EV_KEY, Unhold},
          }},
         {5,
          "Radiation",
          Default,
          Short,
          {
              {1, 0, KEY_LEFTCTRL, EV_KEY, Hold},
              {1, 0, KEY_LEFTSHIFT, EV_KEY, Hold},
              {1, 0, KEY_U, EV_KEY},
              {1, 0, KEY_2, EV_KEY},
              {1, 0, KEY_6, EV_KEY},
              {1, 0, KEY_2, EV_KEY},
              {1, 0, KEY_2, EV_KEY},
              {1, 0, KEY_LEFTCTRL, EV_KEY, Unhold},
              {1, 0, KEY_LEFTSHIFT, EV_KEY, Unhold},
          }},
         {6,
          "Infinity",
          Default,
          Short,
          {
              {1, 0, KEY_LEFTCTRL, EV_KEY, Hold},
              {1, 0, KEY_LEFTSHIFT, EV_KEY, Hold},
              {1, 0, KEY_U, EV_KEY},
              {1, 0, KEY_2, EV_KEY},
              {1, 0, KEY_2, EV_KEY},
              {1, 0, KEY_1, EV_KEY},
              {1, 0, KEY_E, EV_KEY},
              {1, 0, KEY_LEFTCTRL, EV_KEY, Unhold},
              {1, 0, KEY_LEFTSHIFT, EV_KEY, Unhold},
          }},
         {7,
          "Registered sign",
          Default,
          Short,
          {
              {1, 0, KEY_LEFTCTRL, EV_KEY, Hold},
              {1, 0, KEY_LEFTSHIFT, EV_KEY, Hold},
              {1, 0, KEY_U, EV_KEY},
              {1, 0, KEY_A, EV_KEY},
              {1, 0, KEY_E, EV_KEY},
              {1, 0, KEY_LEFTCTRL, EV_KEY, Unhold},
              {1, 0, KEY_LEFTSHIFT, EV_KEY, Unhold},
          }},

         {8, "Shows help", Help, Short, {}},
         {9, "Switches profile to next", SwitchProfile, Short, {}},
     },
     "Unicode symbols",
     0xBBBBBBFF},
    {0,
     {
         {2, "Utility", Default, Long, {{1, 0, KEY_G, EV_KEY}}},
         {3, "Offensive", Default, Long, {{1, 0, KEY_Q, EV_KEY}}},
         {4,
          "Immediate EJECT",
          Default,
          Short,
          {{1, 0, KEY_X, EV_KEY},
           {1, 0, KEY_E, EV_KEY},
           {1, 0, KEY_E, EV_KEY},
           {1, 0, KEY_E, EV_KEY}}},
         {8, "Shows help", Help, Short, {}},
         {9, "Switches profile to next", SwitchProfile, Short, {}},
     },
     "Titanfall 2",
     0x1032FFFF},
};
